name: Docker Build and Push and EC2 Deployment(도커 허브 없이 EC2로 이미지 전달)
on:
  push:
    branches:
      - '**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 깃허브 저장소에서 소스 코드 가져옴
      - name: Checkout Code
        uses: actions/checkout@v3

      # Java 17 환경 설정
      - name: actions/setup-java@v3
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # gradlew에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # gradle로 애플리케이션 빌드
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build and Save Docker Image
        run: |
          IMAGE_NAME=your-app
          TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$TAG .
          docker save $IMAGE_NAME:$TAG -o your-app.tar

      - name: Fix Permissions
        run: chmod 644 ./your-app.tar

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{secrets.EC2_HOST}}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY}}
          source: ./your-app.tar
          target: ~/your-app.tar


      - name: Load Docker Image and Run Container on EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 애플리케이션 컨테이너 실행
            docker load <~/your-app.tar
                  # 로드된 이미지 태그 확인 및 재설정
            docker images | grep your-app:${{ github.sha }} || {
            echo "Image not found with tag, retagging..."
            IMAGE_ID=$(docker images -q | head -n 1)
            docker tag $IMAGE_ID your-app:${{ github.sha }}
            }
            docker stop my-app || true
            docker rm my-app || true
            docker run -d \
              --name my-app \
              --link mysql-container:mysql \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bankDB \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -p 8080:8080 \
              your-app:${{ github.sha }}
